### ISSUE TITLE
baidu link is dead or what?

### ISSUE THREAD

**Issue by githubissogood** [TachibanaYoshino/AnimeGAN#1]
HI I am very interest to know how far AnimGan can beat CartoonGan ,
but the baidu  link (dateset)  is dead .
Can you put it at google drive or mega drive for everyone?
i think that is a problem for everyone interest in your project~

**Comment by Delo001** [comment]
Hi did you ever manage to get the dataset ?
I tried for quite a while just the download would 
not start for me using baidu software.

**Comment by eskat0n-genius** [comment]
Unfortunately, seems like Baidu link is dead again. Could you please update it? I would really-really appreciate it!

**Comment by Desm0nt** [comment]
Anyone have old dataset for reupload? Or atleast samples of dataset's data to create own dataset

**Comment by TachibanaYoshino** [comment]
Baidu Cloud Storage always fails to review my data files, which makes me uncomfortable. Because the Chinese government controls the Internet connection and does not allow citizens to access international good sites such as Google YouTube, I do not have a VPN to connect to Google Cloud Disk. I'm trying to upload data, such as trying it by email.

**Comment by TachibanaYoshino** [comment]
> HI I am very interest to know how far AnimGan can beat CartoonGan ,
> but the baidu link (dateset) is dead .
> Can you put it at google drive or mega drive for everyone?
> i think that is a problem for everyone interest in your project~


I'm sorry to see your question so late. When you asked a question a few months ago, GitHub did not send this dynamic email to remind me, which caused me to not check and resolve it in time. Now, because China ’s Baidu Cloud Disk's unreasonable review of data files has caused the files to become invalid, I am addressing this issue. However, Chinese citizens are restricted from using websites such as Google. I am very sorry for this. I'm very sorry, brother.

**Comment by Desm0nt** [comment]
> Baidu Cloud Storage always fails to review my data files, which makes me uncomfortable. Because the Chinese government controls the Internet connection and does not allow citizens to access international good sites such as Google YouTube, I do not have a VPN to connect to Google Cloud Disk. I'm trying to upload data, such as trying it by email.
I can try to reupload it on some international mirrors (such as google drive, mega and russian yandex cloud) and send you links to it, if you can reupload it to Baidu.

**Comment by TachibanaYoshino** [comment]
> I can try to reupload it on some international mirrors (such as google drive, mega and russian yandex cloud) and send you links to it, if you can reupload it to Baidu.

Now，you can get it, For the dataset, you can upload it by your ways.

**Comment by TachibanaYoshino** [comment]
> Unfortunately, seems like Baidu link is dead again. Could you please update it? I would really-really appreciate it!

Have you downloaded it according to the resubmission?
