### ISSUE TITLE
百度网盘链接已失效

### ISSUE THREAD

**Issue by qweasdzxc110** [TachibanaYoshino/AnimeGAN#3]
亲，看啦你们模型效果很赞，十分好奇数据的样子。
但是给的百度链接已经失效了，请问能再发一个吗？感谢

**Comment by TachibanaYoshino** [comment]
Baidu Cloud Storage always fails to review my data files, which makes me uncomfortable. Because the Chinese government controls the Internet connection and does not allow citizens to access international good sites such as Google YouTube, I do not have a VPN to connect to Google Cloud Disk. I'm trying to upload data, such as trying it by email.

**Comment by TachibanaYoshino** [comment]
> 亲，看啦你们模型效果很赞，十分好奇数据的样子。
> 但是给的百度链接已经失效了，请问能再发一个吗？感谢
Baidu Cloud Storage always fails to review my data files, which makes me uncomfortable. Because the Chinese government controls the Internet connection and does not allow citizens to access international good sites such as Google YouTube, I do not have a VPN to connect to Google Cloud Disk.


> 亲，看啦你们模型效果很赞，十分好奇数据的样子。
> 但是给的百度链接已经失效了，请问能再发一个吗？感谢

![Uploading v2-26eea51a22048f57bca64d753e05088d_hd.png…]()

**Comment by qweasdzxc110** [comment]
> Baidu Cloud Storage always fails to review my data files, which makes me uncomfortable. Because the Chinese government controls the Internet connection and does not allow citizens to access international good sites such as Google YouTube, I do not have a VPN to connect to Google Cloud Disk. I'm trying to upload data, such as trying it by email.

I'm looking for data files, thank you very much

**Comment by TachibanaYoshino** [comment]
> > Baidu Cloud Storage always fails to review my data files, which makes me uncomfortable. Because the Chinese government controls the Internet connection and does not allow citizens to access international good sites such as Google YouTube, I do not have a VPN to connect to Google Cloud Disk. I'm trying to upload data, such as trying it by email.
> 
> I'm looking for data files, thank you very much

Now， do you get it？

**Comment by qweasdzxc110** [comment]
> > > Baidu Cloud Storage always fails to review my data files, which makes me uncomfortable. Because the Chinese government controls the Internet connection and does not allow citizens to access international good sites such as Google YouTube, I do not have a VPN to connect to Google Cloud Disk. I'm trying to upload data, such as trying it by email.
> > 
> > 
> > I'm looking for data files, thank you very much
> 
> Now， do you get it？

yes, the link is active , i'm downloading the dataset. Thank you!
