### ISSUE TITLE
Want to have a conversation with you TachibanaYoshino.

### ISSUE THREAD

**Issue by biswaroop1547** [TachibanaYoshino/AnimeGAN#6]
Would like to have a chat or conversation with you @TachibanaYoshino . Can you please tell me in which social media should I follow you or where can we talk about it?

**Comment by TachibanaYoshino** [comment]
> Would like to have a chat or conversation with you @TachibanaYoshino . Can you please tell me in which social media should I follow you or where can we talk about it?

Baidu Cloud Storage always fails to review my data files, which makes me uncomfortable. Because the Chinese government controls the Internet connection and does not allow citizens to access international good sites such as Google YouTube, I do not have a VPN to connect to Google Cloud Disk. I'm trying to upload data, such as trying it by email.

**Comment by biswaroop1547** [comment]
I can see this situation is really problematic for you, can you kindly share your email then?Would love to have a talk with you. I think I may have one premium Nord VPN account too with a friend of mine, I can try to give that to you too! 
Thanks for replying :)
